export const DEMO_USERS = [
  {
    id: 'demo-1',
    username: 'sarah_k',
    email: 'sarah@example.com',
    profileImageUrl: 'https://ui-avatars.com/api/?name=Sarah+K&background=e8a87c&color=fff&size=128',
    latitude: 41.8827,
    longitude: -87.6233,
    radiusMiles: 3,
  },
  {
    id: 'demo-2',
    username: 'mike_r',
    email: 'mike@example.com',
    profileImageUrl: 'https://ui-avatars.com/api/?name=Mike+R&background=85c1e9&color=fff&size=128',
    latitude: 41.8950,
    longitude: -87.6440,
    radiusMiles: 5,
  },
  {
    id: 'demo-3',
    username: 'jen_t',
    email: 'jen@example.com',
    profileImageUrl: 'https://ui-avatars.com/api/?name=Jen+T&background=82e0aa&color=fff&size=128',
    latitude: 41.8650,
    longitude: -87.6100,
    radiusMiles: 2,
  },
  {
    id: 'demo-4',
    username: 'carlos_m',
    email: 'carlos@example.com',
    profileImageUrl: 'https://ui-avatars.com/api/?name=Carlos+M&background=bb8fce&color=fff&size=128',
    latitude: 41.9100,
    longitude: -87.6550,
    radiusMiles: 4,
  },
  {
    id: 'demo-5',
    username: 'amy_w',
    email: 'amy@example.com',
    profileImageUrl: 'https://ui-avatars.com/api/?name=Amy+W&background=f1948a&color=fff&size=128',
    latitude: 41.8750,
    longitude: -87.6350,
    radiusMiles: 3,
  },
]